#!/usr/bin/env bash
#
# arch-i3-rice.sh — GENERATED by build-rice.sh, do not edit by hand.
# Source of truth: https://github.com/thefoulowl/dotfiles
#
# Minimal dark i3 setup for Arch (X11): theme, picom, alacritty, rofi,
# dunst, themed ly login, i3lock without faillock lockouts, touchpad tap,
# Windows-style Alt+Tab, minimize/restore, one-window-at-a-time workflow.
#
# Safe to re-run: existing files are moved aside as *.bak-<timestamp>.
# Usage: ./arch-i3-rice.sh

set -euo pipefail

# ---- palette: change these to retheme everything ----
BG="#101014"
FG="#d8d8dc"
ACCENT="#7aa2f7"
MUTED="#44475a"
URGENT="#f7768e"

TS="$(date +%Y%m%d-%H%M%S)"
backup() { if [ -e "$1" ] && [ ! -L "$1" ]; then mv "$1" "$1.bak-$TS"; echo "    (backed up existing -> $1.bak-$TS)"; fi; }
palette() {
    sed -i \
        -e "s/101014/${BG#\#}/g" \
        -e "s/d8d8dc/${FG#\#}/g" \
        -e "s/7aa2f7/${ACCENT#\#}/g" \
        -e "s/44475a/${MUTED#\#}/g" \
        -e "s/f7768e/${URGENT#\#}/g" \
        "$1"
}

echo "==> Installing packages (sudo)"
sudo pacman -S --needed --noconfirm \
    i3-wm i3status dmenu alacritty xorg-server xorg-xinit \
    picom ttf-jetbrains-mono-nerd \
    i3lock xss-lock maim brightnessctl rofi dunst libnotify \
    ly python
mkdir -p ~/Pictures

echo "==> Writing user configs"
echo "  $HOME/.config/i3/config"
mkdir -p "$(dirname $HOME/.config/i3/config)"
backup $HOME/.config/i3/config
cat > $HOME/.config/i3/config <<'__DOTFILE_EOF__'
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# i3 defaults this to "yes", meaning the cursor merely passing over a window
# focuses it. That was silently corrupting the Alt+Tab history (mouse drift
# counted as a deliberate switch) — keyboard/clicks only, going forward.
focus_follows_mouse no

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:JetBrainsMono Nerd Font 10

# --- theme: dark minimal ---
set $bg     #101014
set $fg     #d8d8dc
set $accent #7aa2f7
set $muted  #44475a
set $urgent #f7768e

gaps inner 12
gaps outer 4
smart_gaps on
smart_borders on

for_window [class="^.*"] border pixel 2
default_border pixel 2
default_floating_border pixel 2

# class                 border    backgr.   text   indicator  child_border
client.focused           $accent   $accent   $bg    $accent    $accent
client.focused_inactive  $muted    $muted    $fg    $muted     $muted
client.unfocused         $muted    $bg       $fg    $muted     $bg
client.urgent            $urgent   $urgent   $bg    $urgent    $urgent

exec --no-startup-id picom --config ~/.config/picom/picom.conf
exec --no-startup-id xsetroot -solid $bg
# focus-history daemon runs as a systemd --user service instead (more reliable
# than i3's own exec autostart, which wasn't firing reliably on this machine
# for `i3-msg restart` — see i3-focus-history.service)

# screen lock (xss-lock) and notifications (dunst) run as systemd --user
# services instead — i3's own exec autostart isn't reliable on this machine
# for `i3-msg restart` (see i3-focus-history.service for the same fix)

# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# Brightness
bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl set +10%
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl set 10%-

# Screenshots (maim): full screen / region select
bindsym $mod+p exec --no-startup-id maim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
bindsym $mod+Shift+p exec --no-startup-id maim -s ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png

# Lock screen
bindsym $mod+Shift+x exec --no-startup-id i3lock -c 101014

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar

# toggling a tiled window to floating keeps its current (often small) tiled
# size — enforce a floor so it doesn't end up tiny/short.
floating_minimum_size 800 x 500

# start a terminal
# i3 refuses to auto-focus a NEW window while the current one is fullscreen
# (by design, so a video/game isn't interrupted) — drop fullscreen first so
# the new terminal actually gets focus, and shows up in Alt+Tab immediately.
bindsym $mod+Return fullscreen disable; exec alacritty
# ...and every new app window opens as its own maximized window rather than
# splitting the screen with whatever was already there. Scoped to "normal"
# windows so dialogs, file pickers and popups keep their natural size.
for_window [window_type="normal"] fullscreen enable, focus

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec --no-startup-id dmenu_run -nb "$bg" -nf "$fg" -sb "$accent" -sf "$bg" -fn "JetBrainsMono Nerd Font:size=10"

# tap Super alone (no other key) to also open the launcher, Windows-key
# style — xcape (systemd service) turns a solo Super tap into the Menu
# keysym (an unused laptop key), since $mod+anything still needs to work
# normally as every other shortcut
bindsym Menu exec --no-startup-id dmenu_run -nb "$bg" -nf "$fg" -sb "$accent" -sf "$bg" -fn "JetBrainsMono Nerd Font:size=10"
# A more modern dmenu replacement is rofi:
# bindcode $mod+40 exec "rofi -modi drun,run -show drun"
# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
# bindcode $mod+40 exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# minimize / restore via the scratchpad.
# i3 refuses "move scratchpad" on a fullscreen window, so always drop
# fullscreen first. (Shift+minus is the "underscore" keysym on a US layout.)
bindsym $mod+minus fullscreen disable, move scratchpad; fullscreen enable
bindsym $mod+Shift+underscore exec --no-startup-id python3 ~/.config/i3/scripts/focus_history.py --restore

# minimize every window on the current workspace at once (show-desktop)
bindsym $mod+m fullscreen disable; [workspace="__focused__"] move scratchpad

# Alt+Tab, Windows-style: hold Alt, tap Tab to step through windows in
# most-recently-used order (Shift+Tab steps back), release Alt to land.
# (key auto-repeat is throttled inside the script)
bindsym Mod1+Tab exec --no-startup-id python3 ~/.config/i3/scripts/focus_history.py --tab
bindsym Mod1+Shift+Tab exec --no-startup-id python3 ~/.config/i3/scripts/focus_history.py --tab-back
bindsym --release Alt_L exec --no-startup-id python3 ~/.config/i3/scripts/focus_history.py --release
bindsym --release Alt_R exec --no-startup-id python3 ~/.config/i3/scripts/focus_history.py --release

# full fuzzy window list (any workspace) when you'd rather pick by name
bindsym $mod+Shift+Tab exec --no-startup-id rofi -show window

# cycle to previously focused workspace
bindsym $mod+Tab workspace back_and_forth

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
        font pango:JetBrainsMono Nerd Font 10
        position bottom
        separator_symbol " | "
        colors {
                background $bg
                statusline $fg
                separator  $muted

                focused_workspace  $accent $accent $bg
                active_workspace   $muted  $muted  $fg
                inactive_workspace $bg     $bg     $muted
                urgent_workspace   $urgent $urgent $bg
        }
}
__DOTFILE_EOF__
chmod 644 $HOME/.config/i3/config
palette $HOME/.config/i3/config
echo "  $HOME/.config/i3/scripts/focus_history.py"
mkdir -p "$(dirname $HOME/.config/i3/scripts/focus_history.py)"
backup $HOME/.config/i3/scripts/focus_history.py
cat > $HOME/.config/i3/scripts/focus_history.py <<'__DOTFILE_EOF__'
#!/usr/bin/env python3
"""
Tracks window focus order via i3's IPC and gives Alt+Tab Windows-style
cycling: hold Alt, tap Tab to step through windows in most-recently-used
order (Shift+Tab steps back), release Alt to land — maximized.

  --daemon   : run continuously, updating the history file on focus/close
  --tab      : step forward in the cycle  (Alt+Tab press)
  --tab-back : step backward in the cycle (Alt+Shift+Tab press)
  --release  : end the cycle             (Alt key release)
  --restore  : bring back the most recently minimized window, maximized
"""
import json
import os
import subprocess
import sys
import time

STATE_FILE = os.path.expanduser("~/.cache/i3_focus_stack")
CYCLE_FILE = os.path.expanduser("~/.cache/i3_cycle_state")
MAX_HISTORY = 20


def read_stack():
    try:
        with open(STATE_FILE) as f:
            return [line.strip() for line in f if line.strip()]
    except FileNotFoundError:
        return []


def write_stack(stack):
    # write to a temp file then rename, so a concurrent --prev never reads a
    # half-written (truncated) file
    tmp = STATE_FILE + ".tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(stack[:MAX_HISTORY]))
    os.replace(tmp, STATE_FILE)


def seed_stack_from_tree():
    """Every daemon start seeds fresh from whatever windows are currently
    open (ignoring any stale file left from a previous run — those con_ids
    may no longer exist), so Alt+Tab works immediately."""
    result = subprocess.run(["i3-msg", "-t", "get_tree"], capture_output=True, text=True)
    try:
        tree = json.loads(result.stdout)
    except json.JSONDecodeError:
        return
    windows = []
    focused_id = None

    def walk(node, in_dock=False):
        nonlocal focused_id
        # i3bar lives under a "dockarea" node and reports window_type
        # "unknown", so filter structurally — docks can't be focused
        in_dock = in_dock or node.get("type") == "dockarea"
        if node.get("window") and not in_dock:
            con_id = str(node["id"])
            windows.append(con_id)
            if node.get("focused"):
                focused_id = con_id
        for child in node.get("nodes", []) + node.get("floating_nodes", []):
            walk(child, in_dock)

    walk(tree)
    if focused_id and focused_id in windows:
        windows.remove(focused_id)
        windows.insert(0, focused_id)
    if windows:
        write_stack(windows)


def run_daemon():
    seed_stack_from_tree()
    proc = subprocess.Popen(
        ["i3-msg", "-t", "subscribe", "-m", '["window"]'],
        stdout=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    for line in proc.stdout:
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        change = event.get("change")
        # title/fullscreen_mode/move/floating/urgent/mark events must not touch
        # the stack — a terminal whose title spinner flips constantly would
        # otherwise be evicted from history every few milliseconds
        if change not in ("focus", "close"):
            continue
        container = event.get("container", {})
        if container.get("window_type") == "dock":
            continue
        con_id = str(container.get("id"))
        if not con_id or con_id == "None":
            continue
        # while an Alt+Tab cycle is in progress, windows we merely step
        # through must not be promoted — only the one landed on (handled
        # by end_cycle) — otherwise the MRU order gets scrambled
        if change == "focus" and cycle_in_progress():
            continue
        stack = read_stack()
        if con_id in stack:
            stack.remove(con_id)
        if change == "focus":
            stack.insert(0, con_id)
        write_stack(stack)
        if change == "close":
            # whatever inherits focus after a close is a plain tiled window,
            # which would expose the split layout — keep it one-window-at-a-time
            subprocess.run(["i3-msg", "fullscreen enable"], capture_output=True)


def focus_and_maximize(con_id):
    subprocess.run(["i3-msg", "fullscreen disable"])
    result = subprocess.run(
        ["i3-msg", f"[con_id={con_id}] focus, fullscreen enable"],
        capture_output=True, text=True,
    )
    try:
        return json.loads(result.stdout)[0].get("success", False)
    except (json.JSONDecodeError, IndexError, KeyError, AttributeError):
        return False


def read_cycle():
    try:
        with open(CYCLE_FILE) as f:
            snapshot_line, index_line, ts_line = f.read().splitlines()
        return snapshot_line.split(","), int(index_line), float(ts_line)
    except (FileNotFoundError, ValueError):
        return None, None, None


def write_cycle(snapshot, index):
    with open(CYCLE_FILE, "w") as f:
        f.write(",".join(snapshot) + "\n" + str(index) + "\n" + str(time.time()))


# X auto-repeat fires every ~30ms; deliberate taps are far slower. Ignore
# steps closer together than this so holding Tab doesn't race through.
REPEAT_GUARD_SEC = 0.15

# If the Alt-release bind ever fails to fire (e.g. Alt held through some
# other chord), a leftover cycle file would block ALL focus tracking forever.
# Nobody pauses this long mid-cycle, so treat anything older as abandoned.
CYCLE_STALE_SEC = 3.0


def cycle_in_progress():
    snapshot, index, last_ts = read_cycle()
    if snapshot is None:
        return False
    if time.time() - last_ts > CYCLE_STALE_SEC:
        end_cycle()
        return False
    return True


def step_cycle(direction):
    cycle_in_progress()  # discards (and commits) a stale cycle first
    snapshot, index, last_ts = read_cycle()
    if snapshot is None:
        # first tap: freeze the current MRU order for the whole cycle
        snapshot = read_stack()
        if len(snapshot) < 2:
            return
        index = 0
    elif time.time() - last_ts < REPEAT_GUARD_SEC:
        return
    # step, skipping any window that has since closed
    for _ in range(len(snapshot)):
        index = (index + direction) % len(snapshot)
        if focus_and_maximize(snapshot[index]):
            write_cycle(snapshot, index)
            return
    end_cycle()


def end_cycle():
    snapshot, index, _ = read_cycle()
    if snapshot is None:
        return
    os.remove(CYCLE_FILE)
    # promote only the window we landed on
    landed = snapshot[index]
    stack = read_stack()
    if landed in stack:
        stack.remove(landed)
    stack.insert(0, landed)
    write_stack(stack)


def restore_from_scratchpad():
    """Bring back the most recently minimized window, maximized. Unlike a
    bare `scratchpad show` this never hides anything — it only restores."""
    result = subprocess.run(["i3-msg", "-t", "get_tree"], capture_output=True, text=True)
    try:
        tree = json.loads(result.stdout)
    except json.JSONDecodeError:
        return
    hidden = []

    def walk(node, in_scratch=False):
        in_scratch = in_scratch or node.get("name") == "__i3_scratch"
        if node.get("window") and in_scratch:
            hidden.append(str(node["id"]))
        for child in node.get("nodes", []) + node.get("floating_nodes", []):
            walk(child, in_scratch)

    walk(tree)
    if not hidden:
        return
    # prefer the one minimized most recently (highest in focus history)
    stack = read_stack()
    target = next((c for c in stack if c in hidden), hidden[0])
    subprocess.run(["i3-msg", "fullscreen disable"])
    # the scratchpad turns windows floating; put it back in the tiling layer
    # on the way out, otherwise it'd sit above every tiled window forever
    subprocess.run(["i3-msg", f"[con_id={target}] scratchpad show, floating disable, fullscreen enable"])


if __name__ == "__main__":
    if "--daemon" in sys.argv:
        run_daemon()
    elif "--tab" in sys.argv:
        step_cycle(+1)
    elif "--tab-back" in sys.argv:
        step_cycle(-1)
    elif "--release" in sys.argv:
        end_cycle()
    elif "--restore" in sys.argv:
        restore_from_scratchpad()
__DOTFILE_EOF__
chmod 755 $HOME/.config/i3/scripts/focus_history.py
palette $HOME/.config/i3/scripts/focus_history.py
echo "  $HOME/.config/i3/scripts/battery_warn.sh"
mkdir -p "$(dirname $HOME/.config/i3/scripts/battery_warn.sh)"
backup $HOME/.config/i3/scripts/battery_warn.sh
cat > $HOME/.config/i3/scripts/battery_warn.sh <<'__DOTFILE_EOF__'
#!/usr/bin/env bash
# Warn once when the battery drops to the threshold while discharging.
# Runs from battery-warn.timer every couple of minutes.
THRESHOLD=15
STAMP="${XDG_RUNTIME_DIR:-/tmp}/battery-warned"

bat=$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -1)
[ -n "$bat" ] || exit 0

status=$(cat "$bat/status")
level=$(cat "$bat/capacity")

if [ "$status" = "Discharging" ] && [ "$level" -le "$THRESHOLD" ]; then
    if [ ! -e "$STAMP" ]; then
        notify-send -u critical "Battery low" "${level}% remaining — plug in soon"
        touch "$STAMP"
    fi
else
    rm -f "$STAMP"
fi
__DOTFILE_EOF__
chmod 755 $HOME/.config/i3/scripts/battery_warn.sh
palette $HOME/.config/i3/scripts/battery_warn.sh
echo "  $HOME/.config/alacritty/alacritty.toml"
mkdir -p "$(dirname $HOME/.config/alacritty/alacritty.toml)"
backup $HOME/.config/alacritty/alacritty.toml
cat > $HOME/.config/alacritty/alacritty.toml <<'__DOTFILE_EOF__'
[window]
padding = { x = 12, y = 12 }
opacity = 0.92
decorations = "none"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11

[colors.primary]
background = "#101014"
foreground = "#d8d8dc"

[colors.cursor]
text = "#101014"
cursor = "#7aa2f7"

[colors.normal]
black   = "#101014"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#d8d8dc"

[colors.bright]
black   = "#44475a"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#ffffff"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\\u001b\\r"
__DOTFILE_EOF__
chmod 644 $HOME/.config/alacritty/alacritty.toml
palette $HOME/.config/alacritty/alacritty.toml
echo "  $HOME/.config/picom/picom.conf"
mkdir -p "$(dirname $HOME/.config/picom/picom.conf)"
backup $HOME/.config/picom/picom.conf
cat > $HOME/.config/picom/picom.conf <<'__DOTFILE_EOF__'
backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 14;
shadow-opacity = 0.45;
shadow-offset-x = -14;
shadow-offset-y = -14;

corner-radius = 6;
round-borders = 1;

opacity-rule = [
  "92:class_g = 'Alacritty'",
  "100:class_g ?= 'firefox'"
];

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

blur-method = "none";
__DOTFILE_EOF__
chmod 644 $HOME/.config/picom/picom.conf
palette $HOME/.config/picom/picom.conf
echo "  $HOME/.config/rofi/config.rasi"
mkdir -p "$(dirname $HOME/.config/rofi/config.rasi)"
backup $HOME/.config/rofi/config.rasi
cat > $HOME/.config/rofi/config.rasi <<'__DOTFILE_EOF__'
configuration {
    modi: "window";
    font: "JetBrainsMono Nerd Font 11";
    show-icons: false;
}

* {
    bg:      #101014;
    bg-alt:  #17171c;
    fg:      #d8d8dc;
    accent:  #7aa2f7;
    muted:   #44475a;

    background-color: @bg;
    text-color:        @fg;
    border-color:      @accent;
}

window {
    width: 40%;
    border: 2px;
    border-radius: 6px;
    padding: 12px;
    background-color: @bg;
}

mainbox {
    children: [ inputbar, listview ];
    spacing: 10px;
}

inputbar {
    background-color: @bg-alt;
    text-color: @fg;
    padding: 8px 10px;
    border-radius: 4px;
}

listview {
    lines: 8;
    scrollbar: false;
    spacing: 4px;
}

element {
    padding: 6px 10px;
    border-radius: 4px;
}

element selected {
    background-color: @accent;
    text-color: @bg;
}
__DOTFILE_EOF__
chmod 644 $HOME/.config/rofi/config.rasi
palette $HOME/.config/rofi/config.rasi
echo "  $HOME/.config/i3status/config"
mkdir -p "$(dirname $HOME/.config/i3status/config)"
backup $HOME/.config/i3status/config
cat > $HOME/.config/i3status/config <<'__DOTFILE_EOF__'
general {
        colors = true
        interval = 5
        color_good = "#7aa2f7"
        color_degraded = "#e0af68"
        color_bad = "#f7768e"
}

order += "wireless _first_"
order += "ethernet _first_"
order += "battery all"
order += "memory"
order += "tztime local"

wireless _first_ {
        format_up = " %essid"
        format_down = " down"
}

ethernet _first_ {
        format_up = " %ip"
        format_down = ""
}

battery all {
        format = "%status %percentage"
        format_down = ""
        status_chr = ""
        status_bat = ""
        status_full = ""
        low_threshold = 15
}

memory {
        format = " %used"
        threshold_degraded = "1G"
        format_degraded = " %available"
}

tztime local {
        format = " %Y-%m-%d  %H:%M"
}
__DOTFILE_EOF__
chmod 644 $HOME/.config/i3status/config
palette $HOME/.config/i3status/config
echo "  $HOME/.config/dunst/dunstrc"
mkdir -p "$(dirname $HOME/.config/dunst/dunstrc)"
backup $HOME/.config/dunst/dunstrc
cat > $HOME/.config/dunst/dunstrc <<'__DOTFILE_EOF__'
[global]
    monitor = 0
    follow = keyboard
    origin = top-right
    offset = (16, 16)
    width = 360
    height = (0, 160)
    notification_limit = 4

    font = JetBrainsMono Nerd Font 10
    markup = full
    format = "<b>%s</b>\n%b"
    alignment = left
    word_wrap = yes
    ignore_newline = no
    show_indicators = no
    icon_position = off

    frame_width = 2
    frame_color = "#7aa2f7"
    corner_radius = 6
    gap_size = 8
    padding = 12
    horizontal_padding = 14
    separator_height = 0

    idle_threshold = 120
    show_age_threshold = 60
    sort = yes
    stack_duplicates = yes

    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all

[urgency_low]
    background = "#101014"
    foreground = "#d8d8dc"
    frame_color = "#44475a"
    timeout = 5

[urgency_normal]
    background = "#101014"
    foreground = "#d8d8dc"
    frame_color = "#7aa2f7"
    timeout = 8

[urgency_critical]
    background = "#101014"
    foreground = "#f7768e"
    frame_color = "#f7768e"
    timeout = 0
__DOTFILE_EOF__
chmod 644 $HOME/.config/dunst/dunstrc
palette $HOME/.config/dunst/dunstrc
echo "  $HOME/.config/systemd/user/i3-focus-history.service"
mkdir -p "$(dirname $HOME/.config/systemd/user/i3-focus-history.service)"
backup $HOME/.config/systemd/user/i3-focus-history.service
cat > $HOME/.config/systemd/user/i3-focus-history.service <<'__DOTFILE_EOF__'
[Unit]
Description=i3 focus-history daemon for Alt+Tab cycling
After=graphical-session.target

[Service]
Type=simple
Environment=DISPLAY=:0
ExecStart=/usr/bin/python3 %h/.config/i3/scripts/focus_history.py --daemon
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
__DOTFILE_EOF__
chmod 644 $HOME/.config/systemd/user/i3-focus-history.service
palette $HOME/.config/systemd/user/i3-focus-history.service
echo "  $HOME/.config/systemd/user/battery-warn.service"
mkdir -p "$(dirname $HOME/.config/systemd/user/battery-warn.service)"
backup $HOME/.config/systemd/user/battery-warn.service
cat > $HOME/.config/systemd/user/battery-warn.service <<'__DOTFILE_EOF__'
[Unit]
Description=Low battery notification check

[Service]
Type=oneshot
Environment=DISPLAY=:0
ExecStart=%h/.config/i3/scripts/battery_warn.sh
__DOTFILE_EOF__
chmod 644 $HOME/.config/systemd/user/battery-warn.service
palette $HOME/.config/systemd/user/battery-warn.service
echo "  $HOME/.config/systemd/user/battery-warn.timer"
mkdir -p "$(dirname $HOME/.config/systemd/user/battery-warn.timer)"
backup $HOME/.config/systemd/user/battery-warn.timer
cat > $HOME/.config/systemd/user/battery-warn.timer <<'__DOTFILE_EOF__'
[Unit]
Description=Check battery level every 2 minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=2min

[Install]
WantedBy=timers.target
__DOTFILE_EOF__
chmod 644 $HOME/.config/systemd/user/battery-warn.timer
palette $HOME/.config/systemd/user/battery-warn.timer

echo "==> Installing system files (sudo)"
STAGE="$(mktemp -d)"
echo "  $STAGE/i3lock"
mkdir -p "$(dirname $STAGE/i3lock)"
backup $STAGE/i3lock
cat > $STAGE/i3lock <<'__DOTFILE_EOF__'
# PAM configuration file for i3lock. Auth directly against pam_unix, 
# skipping pam_faillock so mistyped unlock attempts never lock the account.
# 
auth       required                    pam_unix.so          try_first_pass nullok
account    required                    pam_unix.so
__DOTFILE_EOF__
chmod 644 $STAGE/i3lock
palette $STAGE/i3lock
sudo install -Dm644 "$STAGE/i3lock" "/etc/pam.d/i3lock"
echo "  $STAGE/30-touchpad.conf"
mkdir -p "$(dirname $STAGE/30-touchpad.conf)"
backup $STAGE/30-touchpad.conf
cat > $STAGE/30-touchpad.conf <<'__DOTFILE_EOF__'
Section "InputClass"
    Identifier "libinput touchpad"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lrm"
EndSection
__DOTFILE_EOF__
chmod 644 $STAGE/30-touchpad.conf
palette $STAGE/30-touchpad.conf
sudo install -Dm644 "$STAGE/30-touchpad.conf" "/etc/X11/xorg.conf.d/30-touchpad.conf"
echo "  $STAGE/config.ini"
mkdir -p "$(dirname $STAGE/config.ini)"
backup $STAGE/config.ini
cat > $STAGE/config.ini <<'__DOTFILE_EOF__'
# Ly supports 24-bit true color with styling, which means each color is a 32-bit value.
# The format is 0xSSRRGGBB, where SS is the styling, RR is red, GG is green, and BB is blue.
# Here are the possible styling options:
# TB_BOLD      0x01000000
# TB_UNDERLINE 0x02000000
# TB_REVERSE   0x04000000
# TB_ITALIC    0x08000000
# TB_BLINK     0x10000000
# TB_HI_BLACK  0x20000000
# TB_BRIGHT    0x40000000
# TB_DIM       0x80000000
# Programmatically, you'd apply them using the bitwise OR operator (|), but because Ly's
# configuration doesn't support using it, you have to manually compute the color value.
# Note that, if you want to use the default color value of the terminal, you can use the
# special value 0x00000000. This means that, if you want to use black, you *must* use
# the styling option TB_HI_BLACK (the RGB values are ignored when using this option).

# Allow empty password or not when authenticating
allow_empty_password = true

# The active animation
# none     -> Nothing
# doom     -> PSX DOOM fire
# matrix   -> CMatrix
# colormix -> Color mixing shader
# gameoflife -> John Conway's Game of Life
# dur_file -> .dur file format (https://github.com/cmang/durdraw/tree/master)
animation = none

# Delay between each animation frame in milliseconds
animation_frame_delay = 5

# Stop the animation after some time
# 0 -> Run forever
# 1..2e12 -> Stop the animation after this many seconds
animation_timeout_sec = 0

# The character used to mask the password
# You can either type it directly as a UTF-8 character (like *), or use a UTF-32
# codepoint (for example 0x2022 for a bullet point)
# If null, the password will be hidden
# Note: you can use a # by escaping it like so: \#
asterisk = *

# The number of failed authentications before a special animation is played... ;)
# If set to 0, the animation will never be played
auth_fails = 10

# Identifier for battery whose charge to display at top left
# Primary battery is usually BAT0 or BAT1
# If set to null, battery status won't be shown
battery_id = BAT1

# Automatic login configuration
# This feature allows Ly to automatically log in a user without password prompt.
# IMPORTANT: Both auto_login_user and auto_login_session must be set for this to work.
# Autologin only happens once at startup - it won't re-trigger after logout.

# PAM service name to use for automatic login
# The default service (ly-autologin) uses pam_permit to allow login without password
# The appropriate platform-specific PAM configuration (ly-autologin) will be used automatically
auto_login_service = ly-autologin

# Session name to launch automatically
# To find available session names, check the .desktop files in:
#   - /usr/share/xsessions/ (for X11 sessions)
#   - /usr/share/wayland-sessions/ (for Wayland sessions)
# Use the filename without .desktop extension, the Name field inside the file or the value of the DesktopNames field
# Examples: "i3", "sway", "gnome", "plasma", "xfce"
# If null, automatic login is disabled
auto_login_session = null

# Username to automatically log in
# Must be a valid user on the system
# If null, automatic login is disabled
auto_login_user = null

# Background color id
bg = 0x00101014

# Change the state and language of the big clock
# none -> Disabled (default)
# en   -> English
# fa   -> Farsi
bigclock = none

# Set bigclock to 12-hour notation.
bigclock_12hr = false

# Set bigclock to show the seconds.
bigclock_seconds = false

# Blank main box background
# Setting to false will make it transparent
blank_box = true

# Border foreground color id
border_fg = 0x007aa2f7

# Title to show at the top of the main box
# If set to null, none will be shown
box_title = null

# Brightness decrease command
brightness_down_cmd = /usr/bin/brightnessctl -q -n s 10%-

# Brightness decrease key combination, or null to disable
brightness_down_key = F5

# Brightness increase command
brightness_up_cmd = /usr/bin/brightnessctl -q -n s +10%

# Brightness increase key combination, or null to disable
brightness_up_key = F6

# Erase password input on failure
clear_password = false

# Format string for clock in top right corner (see strftime specification). Example: %c
# If null, the clock won't be shown
clock = %H:%M

# CMatrix animation foreground color id
cmatrix_fg = 0x0000FF00

# CMatrix animation character string head color id
cmatrix_head_col = 0x01FFFFFF

# CMatrix animation minimum codepoint. It uses a 16-bit integer
# For Japanese characters for example, you can use 0x3000 here
cmatrix_min_codepoint = 0x21

# CMatrix animation maximum codepoint. It uses a 16-bit integer
# For Japanese characters for example, you can use 0x30FF here
cmatrix_max_codepoint = 0x7B

# Color mixing animation first color id
colormix_col1 = 0x00FF0000

# Color mixing animation second color id
colormix_col2 = 0x000000FF

# Color mixing animation third color id
colormix_col3 = 0x20000000

# For custom binds: the horizontal limit in characters for each
# line of custom binds before moving on to the next.
# If null, defaults to the width of the terminal instead.
custom_bind_width = null

# Custom sessions directory
# You can specify multiple directories,
# e.g. /etc/ly/custom-sessions:/usr/share/custom-sessions
custom_sessions = /etc/ly/custom-sessions

# Input box active by default on startup
# Available inputs: info_line, session, login, password
default_input = login

# DOOM animation fire height (1 thru 9)
doom_fire_height = 6

# DOOM animation fire spread (0 thru 4)
doom_fire_spread = 2

# DOOM animation custom top color (low intensity flames)
doom_top_color = 0x009F2707

# DOOM animation custom middle color (medium intensity flames)
doom_middle_color = 0x00C78F17

# DOOM animation custom bottom color (high intensity flames)
doom_bottom_color = 0x00FFFFFF

# Dur file path
dur_file_path = /etc/ly/example.dur

# Dur file alignment
# The dur file can be aligned with a direction and centered easily with the flags below
# Available inputs: topleft, topcenter, topright, centerleft, center, centerright, bottomleft, bottomcenter, bottomright
dur_offset_alignment = center

# Dur offset x direction (value is added to the current position determined by alignment, negatives are supported)
dur_x_offset = 0

# Dur offset y direction (value is added to the current position determined by alignment, negatives are supported)
dur_y_offset = 0

# Set margin to the edges of the DM (useful for curved monitors)
edge_margin = 0

# Error background color id
error_bg = 0x00000000

# Error foreground color id
# Default is red and bold
error_fg = 0x01f7768e

# Foreground color id
fg = 0x00d8d8dc

# Render true colors (if supported)
# If false, output will be in eight-color mode
# All eight-color mode color codes:
# TB_DEFAULT              0x0000
# TB_BLACK                0x0001
# TB_RED                  0x0002
# TB_GREEN                0x0003
# TB_YELLOW               0x0004
# TB_BLUE                 0x0005
# TB_MAGENTA              0x0006
# TB_CYAN                 0x0007
# TB_WHITE                0x0008
# If full color is off, the styling options still work. The colors are
# always 32-bit values with the styling in the most significant byte.
# Note: If using the dur_file animation option and the dur file's color range
# is saved as 256 with this option disabled, the file will not be drawn.
full_color = true

# Game of Life entropy interval (0 = disabled, >0 = add entropy every N generations)
# 0 -> Pure Conway's Game of Life (will eventually stabilize)
# 10 -> Add entropy every 10 generations (recommended for continuous activity)
# 50+ -> Less frequent entropy for more natural evolution
gameoflife_entropy_interval = 10

# Game of Life animation foreground color id
gameoflife_fg = 0x0000FF00

# Game of Life frame delay (lower = faster animation, higher = slower)
# 1-3 -> Very fast animation
# 6 -> Default smooth animation speed
# 10+ -> Slower, more contemplative speed
gameoflife_frame_delay = 6

# Game of Life initial cell density (0.0 to 1.0)
# 0.1 -> Sparse, minimal activity
# 0.4 -> Balanced activity (recommended)
# 0.7+ -> Dense, chaotic patterns
gameoflife_initial_density = 0.4

# Command executed when pressing hibernate key (can be null)
hibernate_cmd = null

# Specifies the key combination used for hibernate
hibernate_key = F4

# Remove main box borders
hide_borders = false

# Remove power management command hints
hide_key_hints = false

# Remove keyboard lock states from the top right corner
hide_keyboard_locks = false

# Remove version number from the top left corner
hide_version_string = false

# Command executed when no input is detected for a certain time
# If null, no command will be executed
inactivity_cmd = null

# Executes a command after a certain amount of seconds
inactivity_delay = 0

# Initial text to show on the info line
# If set to null, the info line defaults to the hostname
initial_info_text = null

# Input boxes length
input_len = 34

# Active language
# Available languages are found in /etc/ly/lang/
lang = en

# Command executed when logging in
# If null, no command will be executed
# Important: the code itself must end with `exec "$@"` in order to launch the session!
# You can also set environment variables in there, they'll persist until logout
login_cmd = null

# Path for login.defs file (used for listing all local users on the system on
# Linux)
login_defs_path = /etc/login.defs

# Command executed when logging out
# If null, no command will be executed
# Important: the session will already be terminated when this command is executed, so
# no need to add `exec "$@"` at the end
logout_cmd = null

# General log file path
ly_log = /var/log/ly.log

# Main box horizontal margin
margin_box_h = 2

# Main box vertical margin
margin_box_v = 1

# Set numlock on/off at startup
numlock = false

# Default path
# If null, ly doesn't set a path
path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Command executed when pressing restart_key
restart_cmd = /sbin/shutdown -r now

# Specifies the key combination used for restart
restart_key = F2

# Save the current desktop and login as defaults, and load them on startup
save = true

# Service name (set to ly to use the provided pam config file)
service_name = ly

# Session log file path
# This will contain stdout and stderr of Wayland sessions
# By default it's saved in the user's home directory
# Important: due to technical limitations, X11, shell sessions as well as
# launching session via KMSCON aren't supported, which means you won't get any
# logs from those sessions.
# If null, no session log will be created
session_log = .local/state/ly-session.log

# Setup command
setup_cmd = /etc/ly/setup.sh

# Show the shell session in the session list
# If false, the shell session will be hidden
shell = true

# Specifies the key combination used for showing the password
show_password_key = F7

# Display the active TTY number (e.g. tty3) to the right of the clock in the top right corner
# If the clock is disabled, the TTY label occupies the top right corner on its own
# If false, the TTY number will not be shown
show_tty = false

# Command executed when pressing shutdown_key
shutdown_cmd = /sbin/shutdown -a now

# Specifies the key combination used for shutdown
shutdown_key = F1

# Command executed when pressing sleep key (can be null)
sleep_cmd = null

# Specifies the key combination used for sleep
sleep_key = F3

# Command executed when starting Ly (before the TTY is taken control of)
# See file at path below for an example of changing the default TTY colors
start_cmd = /etc/ly/startup.sh

# Center the session name.
text_in_center = false

# Default vi mode
# normal   -> normal mode
# insert   -> insert mode
vi_default_mode = normal

# Enable vi keybindings
vi_mode = false

# Wayland desktop environments
# You can specify multiple directories,
# e.g. /usr/share/wayland-sessions:/usr/local/share/wayland-sessions
# If null, Wayland sessions will not be shown
waylandsessions = /usr/share/wayland-sessions

# Xorg server command
# Add the -quiet argument to hide startup logs from the server
x_cmd = /usr/bin/X

# Xorg virtual terminal number
# Mostly useful for FreeBSD where choosing the current TTY causes issues
# If null, the current TTY will be chosen
x_vt = null

# Xorg xauthority edition tool
xauth_cmd = /usr/bin/xauth

# xinitrc
# If null, the xinitrc session will be hidden
xinitrc = ~/.xinitrc

# Xorg desktop environments
# You can specify multiple directories,
# e.g. /usr/share/xsessions:/usr/local/share/xsessions
# If null, X11 sessions will not be shown
xsessions = /usr/share/xsessions

# Custom Commands and Labels:
# The following examples below give an outline for setting up custom commands and labels.
# Unless specified as optional, an option is mandatory.

# Comments preceding with '##' are for documentation.
# Comments preceding with '#' comment out the example INI.

## Declare a command with the F8 binding.
#[cmd:F8]
## The name of the command to show up in Ly.
## Note: "$" in "$brightness_up" fetches the appropriate string from the specified locale file
## and is replaced with the value representing "brightness_up".
## You can see the list of keys in any locale file in /etc/ly/lang.
#cmd = touch /tmp/ly.gaming
#name = custom command $brightness_up

## Declare a label with an ID. This ID should be unique across all labels.
#[lbl:kernel]
#cmd = uname -srn
## Optional, defaulting to 0.
## In frames, the time to re-run the command and update the label.
## If 0, only run once and do not refresh afterwards
#refresh = 0
__DOTFILE_EOF__
chmod 644 $STAGE/config.ini
palette $STAGE/config.ini
sudo install -Dm644 "$STAGE/config.ini" "/etc/ly/config.ini"
rm -rf "$STAGE"
# ly battery id is machine-specific
BAT="$(basename "$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -1)" 2>/dev/null || true)"
sudo sed -i "s|^battery_id = .*|battery_id = ${BAT:-null}|" /etc/ly/config.ini

echo "==> Enabling services"
systemctl --user daemon-reload
systemctl --user enable --now i3-focus-history.service battery-warn.timer
sudo systemctl enable ly@tty1.service

echo
echo "Done. Reboot for the ly login screen + touchpad tap-to-click. \$mod = Super."
echo "Alt+Tab cycles windows (hold Alt, tap Tab, release to land), \$mod+minus"
echo "minimizes, \$mod+Shift+underscore restores, \$mod+m minimizes everything,"
echo "\$mod+Shift+Tab is the rofi window picker, \$mod+f toggles fullscreen."
echo "If ~/.bash_profile has an old 'exec startx', remove it — ly owns X now."
