#!/usr/bin/env bash
#
# Generate arch-i3-rice.sh: a single self-contained script that reproduces
# this whole setup with no clone needed. Every config file in the repo is
# embedded verbatim, so the standalone script can never drift from the repo.
#
#   ./build-rice.sh        # writes ./arch-i3-rice.sh

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
OUT=arch-i3-rice.sh

# palette as it appears literally in the config files; the generated script
# exposes these as editable variables and rewrites the files on install
declare -A PALETTE=(
    [BG]=101014 [FG]=d8d8dc [ACCENT]=7aa2f7 [MUTED]=44475a [URGENT]=f7768e
)

# user files: repo path -> install path (relative to $HOME)
USER_FILES=(
    config/i3/config
    config/i3/scripts/focus_history.py
    config/i3/scripts/battery_warn.sh
    config/alacritty/alacritty.toml
    config/picom/picom.conf
    config/rofi/config.rasi
    config/i3status/config
    config/dunst/dunstrc
    config/systemd/user/i3-focus-history.service
    config/systemd/user/battery-warn.service
    config/systemd/user/battery-warn.timer
    config/systemd/user/xss-lock.service
    config/systemd/user/xcape.service
)
# system files: repo path -> absolute install path
SYSTEM_FILES=(
    etc/pam.d/i3lock
    etc/X11/xorg.conf.d/30-touchpad.conf
    etc/ly/config.ini
)

emit_file() {  # emit_file <repo path> <dest path expr> <mode>
    local src=$1 dest=$2 mode=$3
    cat <<EOF
echo "  $dest"
mkdir -p "\$(dirname $dest)"
backup $dest
cat > $dest <<'__DOTFILE_EOF__'
$(cat "$src")
__DOTFILE_EOF__
chmod $mode $dest
palette $dest
EOF
}

{
cat <<'HEADER'
#!/usr/bin/env bash
#
# arch-i3-rice.sh — GENERATED by build-rice.sh, do not edit by hand.
# Source of truth: https://github.com/thefoulowl/dotfiles
#
# Minimal dark i3 setup for Arch (X11): theme, picom, alacritty, rofi,
# dunst, themed ly login, i3lock without faillock lockouts, touchpad tap,
# Windows-style Alt+Tab, minimize/restore, one-window-at-a-time workflow.
#
# Safe to re-run: existing files are moved aside as *.bak-<timestamp>.
# Usage: ./arch-i3-rice.sh

set -euo pipefail

# ---- palette: change these to retheme everything ----
HEADER
for k in BG FG ACCENT MUTED URGENT; do echo "$k=\"#${PALETTE[$k]}\""; done
cat <<'BODY'

TS="$(date +%Y%m%d-%H%M%S)"
backup() { if [ -e "$1" ] && [ ! -L "$1" ]; then mv "$1" "$1.bak-$TS"; echo "    (backed up existing -> $1.bak-$TS)"; fi; }
palette() {
    sed -i \
BODY
for k in BG FG ACCENT MUTED URGENT; do
    echo "        -e \"s/${PALETTE[$k]}/\${$k#\\#}/g\" \\"
done
cat <<'BODY'
        "$1"
}

echo "==> Installing packages (sudo)"
sudo pacman -S --needed --noconfirm \
    i3-wm i3status dmenu alacritty xorg-server xorg-xinit \
    picom ttf-jetbrains-mono-nerd \
    i3lock xss-lock maim brightnessctl rofi dunst libnotify xcape \
    ly python
mkdir -p ~/Pictures

echo "==> Writing user configs"
BODY
for f in "${USER_FILES[@]}"; do
    dest="\$HOME/.${f}"          # config/x -> $HOME/.config/x
    mode=644; [[ $f == *.sh || $f == *.py ]] && mode=755
    emit_file "$f" "$dest" "$mode"
done
cat <<'BODY'

echo "==> Installing system files (sudo)"
STAGE="$(mktemp -d)"
BODY
for f in "${SYSTEM_FILES[@]}"; do
    emit_file "$f" "\$STAGE/$(basename "$f")" 644
    echo "sudo install -Dm644 \"\$STAGE/$(basename "$f")\" \"/$f\""
done
cat <<'BODY'
rm -rf "$STAGE"
# ly battery id is machine-specific
BAT="$(basename "$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -1)" 2>/dev/null || true)"
sudo sed -i "s|^battery_id = .*|battery_id = ${BAT:-null}|" /etc/ly/config.ini

echo "==> Enabling services"
systemctl --user daemon-reload
systemctl --user enable --now i3-focus-history.service battery-warn.timer xss-lock.service xcape.service
sudo systemctl enable ly@tty1.service

echo
echo "Done. Reboot for the ly login screen + touchpad tap-to-click. \$mod = Super,"
echo "or tap it alone for the launcher too. Alt+Tab cycles windows (hold Alt,"
echo "tap Tab, release to land), \$mod+minus"
echo "minimizes, \$mod+Shift+underscore restores, \$mod+m minimizes everything,"
echo "\$mod+Shift+Tab is the rofi window picker, \$mod+f toggles fullscreen."
echo "If ~/.bash_profile has an old 'exec startx', remove it — ly owns X now."
BODY
} > "$OUT"
chmod +x "$OUT"
bash -n "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
