backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 14;
shadow-opacity = 0.45;
shadow-offset-x = -14;
shadow-offset-y = -14;

corner-radius = 6;
round-borders = 1;

opacity-rule = [
  "92:class_g = 'Alacritty'",
  "100:class_g ?= 'firefox'"
];

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

blur-method = "none";
